root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app.exe ./cmd"
  bin = "tmp/app.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
