apiVersion: v1
kind: ConfigMap
metadata:
  name: subscout-config
data:
  DB_HOST: subscout.cnw4iyq60t8d.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: subscout
  APP_ENV: development
  PORT: "8080"
